name: Deploy FrontEnd to Server

on:
  push:
    branches:
      - main   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  Clone repo
        uses: actions/checkout@v3

      - name:  Install dependencies
        run: npm install

      - name:  Build project
        run: npm run build

      - name:  Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 31.97.37.129
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: /home/edulandacademy/web/interno.blog/public_html/
